package com.u91porn.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.u91porn.data.model.Category;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORY".
*/
public class CategoryDao extends AbstractDao<Category, Long> {

    public static final String TABLENAME = "CATEGORY";

    /**
     * Properties of entity Category.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CategoryType = new Property(1, int.class, "categoryType", false, "CATEGORY_TYPE");
        public final static Property CategoryName = new Property(2, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property CategoryValue = new Property(3, String.class, "categoryValue", false, "CATEGORY_VALUE");
        public final static Property CategoryUrl = new Property(4, String.class, "categoryUrl", false, "CATEGORY_URL");
        public final static Property SortId = new Property(5, Integer.class, "sortId", false, "SORT_ID");
        public final static Property IsShow = new Property(6, boolean.class, "isShow", false, "IS_SHOW");
    }


    public CategoryDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CATEGORY_TYPE\" INTEGER NOT NULL ," + // 1: categoryType
                "\"CATEGORY_NAME\" TEXT," + // 2: categoryName
                "\"CATEGORY_VALUE\" TEXT," + // 3: categoryValue
                "\"CATEGORY_URL\" TEXT," + // 4: categoryUrl
                "\"SORT_ID\" INTEGER," + // 5: sortId
                "\"IS_SHOW\" INTEGER NOT NULL );"); // 6: isShow
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Category entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCategoryType());
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(3, categoryName);
        }
 
        String categoryValue = entity.getCategoryValue();
        if (categoryValue != null) {
            stmt.bindString(4, categoryValue);
        }
 
        String categoryUrl = entity.getCategoryUrl();
        if (categoryUrl != null) {
            stmt.bindString(5, categoryUrl);
        }
 
        Integer sortId = entity.getSortId();
        if (sortId != null) {
            stmt.bindLong(6, sortId);
        }
        stmt.bindLong(7, entity.getIsShow() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Category entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCategoryType());
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(3, categoryName);
        }
 
        String categoryValue = entity.getCategoryValue();
        if (categoryValue != null) {
            stmt.bindString(4, categoryValue);
        }
 
        String categoryUrl = entity.getCategoryUrl();
        if (categoryUrl != null) {
            stmt.bindString(5, categoryUrl);
        }
 
        Integer sortId = entity.getSortId();
        if (sortId != null) {
            stmt.bindLong(6, sortId);
        }
        stmt.bindLong(7, entity.getIsShow() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Category readEntity(Cursor cursor, int offset) {
        Category entity = new Category( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // categoryType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // categoryName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // categoryValue
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // categoryUrl
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // sortId
            cursor.getShort(offset + 6) != 0 // isShow
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Category entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategoryType(cursor.getInt(offset + 1));
        entity.setCategoryName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCategoryValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCategoryUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSortId(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setIsShow(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Category entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Category entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Category entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
